name: Terraform_CI_CD

permissions:
  contents: read

on:
  push:
    branches:
      - main
      - 'feature/**'

  pull_request:
    branches:
      - main


jobs:

  # ============================================================
  # 1. TERRAFORM VALIDATION
  # ============================================================

  terraform_validation:
    name: Terraform Validation
    runs-on: ubuntu-latest

    steps:

      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        working-directory: Environment/dev
        run: terraform init

      - name: Terraform Format Check
        working-directory: Environment/dev
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: Environment/dev
        run: terraform validate


  # ============================================================
  # 2. TERRAFORM PLAN
  # ============================================================

  terraform_plan_preview:
    name: Terraform Plan
    needs: terraform_validation
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        working-directory: Environment/dev
        run: terraform init

      - name: Terraform Plan
        working-directory: Environment/dev
        run: terraform plan -out=dev.tfplan -var-file=terraform.tfvars

      - name: Generate Human Readable Plan
        working-directory: Environment/dev
        run: terraform show dev.tfplan > plan.txt

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: |
            Environment/dev/dev.tfplan
            Environment/dev/plan.txt


  # ============================================================
  # 3. TERRAFORM APPLY
  # ONLY AFTER MERGE TO MAIN
  # ============================================================

  terraform_apply:
    name: Terraform Apply
    needs: terraform_plan_preview

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    environment: dev

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        working-directory: Environment/dev
        run: terraform init

      - name: Terraform Plan
        working-directory: Environment/dev
        run: terraform plan -out=dev.tfplan -var-file=terraform.tfvars

      - name: Terraform Apply
        working-directory: Environment/dev
        run: terraform apply -auto-approve dev.tfplan