name: Terraform_CI_CD
permissions:
  contents: read
on:
  push:
    branches:
      - main
      - 'feature/**'

  pull_request:
    branches:
      - main


jobs:

  # ============================================================
  # 1. TERRAFORM VALIDATION
  # ============================================================

  terraform_validation:
    name: Terraform Validation
    runs-on: ubuntu-latest ########github ak vm allocate kareg---runner-----github runner 

    steps:

      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt

      - name: Terraform Validate
        run: terraform validate


  # ============================================================
  # 2. SECURITY SCAN
  # ============================================================

  terraform_security_scan:
    name: Terraform Security Scan
    needs: terraform_validation
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Initialize TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint

      - name: Install Checkov
        run: pip3 install checkov

      - name: Run Checkov
        run: checkov -d .


  # ============================================================
  # 3. TERRAFORM PLAN
  # Runs on feature push, PR and main
  # ============================================================

  terraform_plan_preview:
    name: Terraform Plan
    needs: terraform_security_scan
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=dev.tfplan -var-file=dev.tfvars

      - name: Generate Human Readable Plan
        run: terraform show dev.tfplan > plan.txt

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: |
            dev.tfplan
            plan.txt


  # ============================================================
  # 4. TERRAFORM APPLY
  # ONLY AFTER MERGE TO MAIN
  # ============================================================

  terraform_apply:
    name: Terraform Apply
    needs: terraform_plan_preview

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    environment: dev

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=dev.tfplan -var-file=dev.tfvars

      - name: Terraform Apply
        run: terraform apply -auto-approve dev.tfplan